// <auto-generated />
using System;
using BackendApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260216190049_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 16, 19, 0, 49, 666, DateTimeKind.Utc).AddTicks(2069),
                            Description = "Electronic devices and accessories",
                            Name = "Electronics",
                            UpdatedAt = new DateTime(2026, 2, 16, 19, 0, 49, 666, DateTimeKind.Utc).AddTicks(2070)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 16, 19, 0, 49, 666, DateTimeKind.Utc).AddTicks(2072),
                            Description = "Books and publications",
                            Name = "Books",
                            UpdatedAt = new DateTime(2026, 2, 16, 19, 0, 49, 666, DateTimeKind.Utc).AddTicks(2072)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 16, 19, 0, 49, 666, DateTimeKind.Utc).AddTicks(2073),
                            Description = "Apparel and fashion items",
                            Name = "Clothing",
                            UpdatedAt = new DateTime(2026, 2, 16, 19, 0, 49, 666, DateTimeKind.Utc).AddTicks(2074)
                        });
                });

            modelBuilder.Entity("BackendApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 16, 19, 0, 49, 666, DateTimeKind.Utc).AddTicks(2150),
                            Description = "High-performance laptop",
                            Name = "Laptop",
                            Price = 999.99m,
                            Stock = 15,
                            UpdatedAt = new DateTime(2026, 2, 16, 19, 0, 49, 666, DateTimeKind.Utc).AddTicks(2150)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 16, 19, 0, 49, 666, DateTimeKind.Utc).AddTicks(2152),
                            Description = "Latest smartphone model",
                            Name = "Smartphone",
                            Price = 699.99m,
                            Stock = 25,
                            UpdatedAt = new DateTime(2026, 2, 16, 19, 0, 49, 666, DateTimeKind.Utc).AddTicks(2152)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 16, 19, 0, 49, 666, DateTimeKind.Utc).AddTicks(2153),
                            Description = "Learn programming fundamentals",
                            Name = "Programming Book",
                            Price = 49.99m,
                            Stock = 50,
                            UpdatedAt = new DateTime(2026, 2, 16, 19, 0, 49, 666, DateTimeKind.Utc).AddTicks(2153)
                        });
                });

            modelBuilder.Entity("BackendApi.Models.Product", b =>
                {
                    b.HasOne("BackendApi.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BackendApi.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
